name: Android CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
      uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # Android SDK + Build-Tools installieren und Lizenzen akzeptieren
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          api-level: 34
          cmake: false
          ndk: false

      # Gradle ohne Wrapper verwenden
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.7

      - name: Build Debug APK
        run: gradle assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: FamilienOptimizer-debug
          path: app/build/outputs/apk/debug/*.apk
