name: Android CI (Debug)

on:
  push:
    branches: [ main ]      # baut automatisch bei Push auf main
  pull_request:             # baut bei PRs
  workflow_dispatch:        # manuell startbar

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Set up Android SDK (API 34)
        uses: android-actions/setup-android@v3
        with:
          api-level: 34

      - name: Accept licenses & install packages
        shell: bash
        run: |
          yes | sdkmanager --licenses
          sdkmanager --install "platform-tools" "platforms;android-34" || true
          # Build-Tools 34: versuche 34.0.0, sonst 34.0.2
          sdkmanager --install "build-tools;34.0.0" || sdkmanager --install "build-tools;34.0.2"

      # Gradle vorbereiten (funktioniert auch, wenn kein Wrapper eingecheckt ist)
      - name: Set up Gradle 8.7
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.7

      - name: Generate Gradle wrapper if missing
        shell: bash
        run: |
          if [ ! -f "./gradlew" ]; then
            gradle wrapper --gradle-version 8.7
          fi
          chmod +x ./gradlew
          ./gradlew --version

      - name: Build Debug APK
        run: ./gradlew clean :app:assembleDebug --stacktrace --info

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: FamilienOptimizer-debug
          path: |
            app/build/outputs/apk/debug/*.apk
            **/build/outputs/apk/debug/*.apk
          if-no-files-found: error
          
